# Generated by Django 5.0.7 on 2024-07-26 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarrinhoDeCompras',
            new_name='CarrinhoDeCompra',
        ),
    ]
